#!/bin/bash
echo "=== KIEM TRA NODE.JS/NPM ==="
echo ""
echo "1. Node.js:"
which node && node --version || echo "Node.js khong tim thay"
echo ""
echo "2. npm:"
which npm && npm --version || echo "npm khong tim thay"
echo ""
echo "3. PM2:"
which pm2 && pm2 --version || echo "PM2 khong tim thay"
echo ""
echo "4. NVM:"
[ -f ~/.nvm/nvm.sh ] && echo "NVM duoc cai dat" || echo "NVM khong co"
echo ""
echo "5. System Node.js package:"
dpkg -l 2>/dev/null | grep -i nodejs || echo "Khong co system nodejs package"
echo ""
