#!/usr/bin/env python3
"""
Convert cookies.txt from semicolon-separated format to Netscape format
Netscape format is required by --browser file option in main.py
"""
import os
import sys
from datetime import datetime

def convert_to_netscape(input_file='../cookies.txt', output_file='cookies.txt'):
    """
    Convert cookies from format:
      key1=value1;key2=value2;key3=value3
    
    To Netscape format:
      # Netscape HTTP Cookie File
      domain    flag    path    secure    expiration    name    value
    """
    
    if not os.path.exists(input_file):
        print(f"❌ Input file not found: {input_file}")
        return False
    
    # Read input cookies
    with open(input_file, 'r', encoding='utf-8') as f:
        cookie_string = f.read().strip()
    
    print(f"📖 Reading from: {input_file}")
    print(f"   Length: {len(cookie_string)} chars")
    
    # Parse cookies
    cookies = {}
    for item in cookie_string.split(';'):
        item = item.strip()
        if '=' in item:
            key, value = item.split('=', 1)
            cookies[key.strip()] = value.strip()
    
    print(f"   Parsed: {len(cookies)} cookies")
    
    # Write to Netscape format
    with open(output_file, 'w', encoding='utf-8') as f:
        # Write header
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by convert_cookies.py\n")
        f.write("# Edit at your own risk.\n\n")
        
        # Set domain and expiration (far future: year 2099)
        domain = "samsungu.udemy.com"
        expiration = "4102444800"  # 2099-12-31
        
        # Write each cookie
        for name, value in cookies.items():
            # Format: domain  flag  path  secure  expiration  name  value
            # flag: TRUE if accessible to all hosts within domain, FALSE otherwise
            # secure: TRUE if HTTPS only, FALSE otherwise
            flag = "FALSE"  # Only samsungu.udemy.com
            path = "/"
            secure = "TRUE"  # HTTPS only
            
            line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            f.write(line)
    
    print(f"✅ Written to: {output_file}")
    print(f"   Format: Netscape HTTP Cookie File")
    
    # Verify file
    with open(output_file, 'r') as f:
        lines = f.readlines()
        cookie_lines = [l for l in lines if not l.startswith('#') and l.strip()]
        print(f"   Cookies: {len(cookie_lines)} lines")
    
    return True

if __name__ == '__main__':
    print("🔄 Converting cookies to Netscape format...")
    print("=" * 60)
    
    success = convert_to_netscape()
    
    if success:
        print("\n" + "=" * 60)
        print("✅ SUCCESS! Cookies converted to Netscape format")
        print("=" * 60)
        print("\nNow you can use:")
        print("  python3 main.py -c <URL> --browser file ...")
        print("\nThe main.py script will automatically load cookies.txt")
    else:
        print("\n❌ FAILED to convert cookies")
        sys.exit(1)
